server:
  max-http-header-size: 8096
  port: 9302
spring:
  application:
    name: travel-moudel-user
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
  datasource:
    url: jdbc:mysql://localhost:3306/Travel
    username: travel
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      pool-name: DataHikariCP
      minimum-idle: 5
      idle-timeout: 100000
      maximum-pool-size: 10
      auto-commit: true
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1
  #email
  mail:
    host: smtp.mxhichina.com
    username: admin@ashes.vip
    password: CAOshunmiao6moe
    port: 465
    #设置为SSL协议
    properties:
      mail:
        smtp:
          socketFactory:
            class: javax.net.ssl.SSLSocketFactory
      from: admin@ashes.vip
  servlet:
    multipart:
      # 最大支持文件大小
      max-file-size: 1000MB
      # 最大支持请求大小
      max-request-size: 1000MB

mybatis-plus:
  # 在classpath前添加星号可以使项目热加载成功
  # 自定义xml sql文件需要配置这个
  mapper-locations: classpath:mapper/*.xml
  global-config:
    db-config:
      #主键类型
      id-type: auto
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    # 这个配置会将执行的sql打印出来，在开发或测试的时候可以用
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  type-aliases-package: vip.ashes.travel
#    配置基础包名



# 配置你的又拍云
up-yun:
  user-name: loveliness
  password: CKKSR0F6Y09agZ0qEdPLv99eZgGbC1mY
  bucket: loveliness

logging:
  level:
    org:
      springframework:
        boot:
          autoconfigure: ERROR
debug: true
