server:
  port: 9303
spring:
  redis:
    database: 0
    port: 6379
    host: localhost
    password:
  datasource:
    url: jdbc:mysql://localhost:3306/Travel
    username: travel
    password: 123456