server:
  port: 9201
spring:
  profiles:
    active: dev
  application:
    name: travel-gateway
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    gateway:
      routes: #配置路由路径
        - id: travel-api-route
          uri: lb://travel-api
          predicates:
            - Path=/api/**
          filters:
            - StripPrefix=1
        - id: travel-auth-route
          uri: lb://travel-auth
          predicates:
            - Path=/auth/**
          filters:
            - StripPrefix=1
        - id: travel-moudel-system-route
          uri: lb://travel-moudel-system
          predicates:
            - Path=/system/**
          filters:
            - StripPrefix=1
        - id: travel-moudel-user-route
          uri: lb://travel-moudel-user
          predicates:
            - Path=/user/**
          filters:
            - StripPrefix=1
      discovery:
        locator:
          enabled: true #开启从注册中心动态创建路由的功能
          lower-case-service-id: true #使用小写服务名，默认是大写
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: 'http://localhost:9401/rsa/publicKey' #配置RSA的公钥访问地址
  redis:
    database: 0
    port: 6379
    host: localhost
    password:
secure:
  ignore:
    urls: #配置白名单路径
      - "/auth/**"
      - "/user/auth/**"
