version: "3"
services:
  GateWay:
    image: registry.cn-hangzhou.aliyuncs.com/loveliness/travel-gateway:1.0-SNAPSHOT
    ports:
      - "9201:9201"
    restart: always
    container_name: travel-gateway
  Auth:
    image: registry.cn-hangzhou.aliyuncs.com/loveliness/travel-auth:1.0-SNAPSHOT
    ports:
      - "9401:9401"
    restart: always
    container_name: travel-auth
    depends_on:
      - GateWay
  System:
    image: registry.cn-hangzhou.aliyuncs.com/loveliness/travel-modules-system:1.0-SNAPSHOT
    ports:
      - "9301:9301"
    restart: always
    container_name: travel-system
    depends_on:
      - GateWay
      - Auth
  User:
    image: registry.cn-hangzhou.aliyuncs.com/loveliness/travel-modules-user:1.0-SNAPSHOT
    ports:
      - "9302:9302"
    restart: always
    container_name: travel-user
    depends_on:
      - GateWay
      - Auth
  Map:
    image: registry.cn-hangzhou.aliyuncs.com/loveliness/travel-modules-map:1.0-SNAPSHOT
    ports:
      - "9303:9303"
    restart: always
    container_name: travel-map
    depends_on:
      - GateWay
      - Auth
  Pay:
    image: registry.cn-hangzhou.aliyuncs.com/loveliness/travel-modules-pay:1.0-SNAPSHOT
    ports:
      - "9304:9304"
    restart: always
    container_name: travel-pay
    depends_on:
      - GateWay
      - Auth
